story9/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story9app.urls')),
]

story9app/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'story9app'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', LoginView.as_view(), name='login'),
    path('register/', views.register, name='register'),
    path('logout/', LogoutView.as_view(next_page = 'story9app:dashboard'), name='logout'),
]

story9app/models.py
from django.db import models

# Create your models here.

story9app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def homepage(request):
    return render(request, 'homepage.html')
    
@login_required
def dashboard(request):
    return render(request, 'dashboard.html')

def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('story9app:login')
    else:
        form = UserCreationForm()
    return render(request, 'registration/register.html', {'form' : form})

story9app/templates/dashboard.html
{% extends 'homepage.html' %}

{% block content %}
    <h1 id="welcome">Welcome, {{user.username}}</h1>
    <a id="logout" href="{% url 'story9app:login' %}"><button>Log Out</button></a>
{% endblock %}

story9app/templates/homepage.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>My Website</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/web.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    </head>
    <body>
        {% block content %}
            <h1 id="welcome">Welcome!</h1>
            {% if user.is_authenticated %}
                <a href="{% url 'story9app:login' %}"><button>Log Out</button></a>
                {% else %}
                <div class="col-12 col-md-3" id="login">
                    <a href="{% url 'story9app:login' %}"><button>Log In</button></a>
                    <a href="{% url 'story9app:register' %}"><button>Register</button></a>
                </div>
            {% endif %}
        {% endblock %}
    </body>
</html>